CREATE TABLE IF NOT EXISTS mpa (
                        mpa_id INTEGER PRIMARY KEY,
                        mpa_name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS films
(
    film_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_name    varchar(255) NOT NULL,
    description  varchar(200),
    release_date date         NOT NULL,
    duration     int          NOT NULL,
    mpa_id       int
    );

CREATE TABLE IF NOT EXISTS genres
(
    genre_id   INTEGER PRIMARY KEY,
    genre_name varchar(255) NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS genre_vs_film
(
    film_id  INTEGER REFERENCES films (film_id) ON DELETE CASCADE,
    genre_id int REFERENCES genres (genre_id) ON DELETE RESTRICT,
    PRIMARY KEY (film_id, genre_id)
    );

CREATE TABLE IF NOT EXISTS directors (
    director_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    director_name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS director_vs_film (
    film_id  INTEGER REFERENCES films (film_id) ON DELETE CASCADE,
    director_id int REFERENCES directors (director_id) ON DELETE RESTRICT,
    PRIMARY KEY (film_id, director_id)
);

CREATE TABLE IF NOT EXISTS users
(
    user_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    varchar(255) NOT NULL UNIQUE,
    login    varchar(255) NOT NULL,
    user_name     varchar(255),
    birthday date
    );

CREATE TABLE IF NOT EXISTS likes_vs_film
(
    film_id  INTEGER REFERENCES films (film_id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users (user_id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
    );

CREATE TABLE IF NOT EXISTS friends_vs_users
(
    user_id INTEGER REFERENCES users (user_id) ON DELETE CASCADE,
    friend_id INTEGER REFERENCES users (user_id) ON DELETE CASCADE
);

create TABLE IF NOT EXISTS reviews
    (
    review_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_content varchar(255) NOT NULL,
    isPositive BOOLEAN NOT NULL,
    user_id INTEGER REFERENCES users (user_id) ON delete CASCADE,
    film_id INTEGER REFERENCES films (film_id) ON delete CASCADE,
    useful INTEGER DEFAULT 0
    );

create TABLE IF NOT EXISTS review_likes
(
    review_id INTEGER REFERENCES reviews (review_id) ON delete CASCADE,
    user_id INTEGER REFERENCES users (user_id) ON delete CASCADE
    );

create TABLE IF NOT EXISTS review_dislikes
(
    review_id INTEGER REFERENCES reviews (review_id) ON delete CASCADE,
    user_id INTEGER REFERENCES users (user_id) ON delete CASCADE
    );
